[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
command = "kitty --class kitty-dropterm -e sh -c 'exec $SHELL'"
class = "kitty-dropterm"
position = "5% 5%"
size = "90% 90%"
offset = "120%"

[scratchpads.term2]
command = "kitty --class kitty-dropterm2 -e sh -c 'exec $SHELL'"
class = "kitty-dropterm2"
position = "5% 5%"
size = "90% 90%"
offset = "120%"

[scratchpads.homeassistant]
command = "brave --app=https://home.clownweb.net"
match_by = "initialTitle"
initialTitle = "home.clownweb.net_/"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

[scratchpads.gpt]
command = "brave --app=https://chat.openai.com"
match_by = "initialTitle"
initialTitle = "chat.openai.com_/"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

[scratchpads.todo]
command = "brave --app=https://todoist.com"
match_by = "initialTitle"
initialTitle = "todoist.com_/"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

[scratchpads.gmail]
command = "brave --app=https://gmail.com"
match_by = "initialTitle"
initialTitle = "gmail.com_/"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

[scratchpads.outlook]
command = "brave --app=https://outlook.office365.com"
match_by = "initialTitle"
initialTitle = "outlook.office365.com_/"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

[scratchpads.calendar]
command = "brave --app=https://calendar.google.com/calendar/u/0/r?pli=1"
match_by = "initialTitle"
initialTitle = "calendar.google.com_/calendar/u/0/r"
position = "5% 5%"
size = "90% 90%"
process_tracking = false

