
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: "https://homeassistant.clownweb.net"
  internal_url: "http://homeassistant:8123"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
