#!/bin/sh

# Navigate to your repository
cd ~/.dotfiles || exit

# Check for changes and pull if there are any
git fetch origin
if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
  git pull origin main # Pull changes from the main branch
fi
