#!/bin/sh

rclone sync server:/home/admin/config /mnt/Backup/server/config --ignore-size --checksum
rclone sync server:/home/admin/services /mnt/Backup/server/services --ignore-size --checksum
rclone sync server:/mnt/tank/immich /mnt/Backup/server/immich --ignore-size --checksum
rclone sync server:/mnt/tank/syncthing /mnt/Backup/server/syncthing --ignore-size --checksum

