#!/bin/sh

WALLPAPER_DIR="$HOME/.wallpapers"
WALLPAPER_DEST="$HOME/.wallpaper"

# Randomly select a wallpaper
WALLPAPER=$(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" -o -iname "*.webp" \) | shuf -n 1)

# Exit if no wallpaper is found
if [ -z "$WALLPAPER" ]; then
    echo "No wallpaper found in $WALLPAPER_DIR"
    exit 1
fi

echo "Selected wallpaper: $WALLPAPER"

# Copy the wallpaper to ~/.wallpaper
cp "$WALLPAPER" "$WALLPAPER_DEST"

# Set the wallpaper with hyprpaper
hyprctl hyprpaper preload $WALLPAPER
hyprctl hyprpaper wallpaper $WALLPAPER
#hyprctl hyprpaper reload ,"$HOME/.wallpaper"

~/.system/scripts/set-theme-from-wallpaper
