#!/bin/sh

# Source and destination directories
SOURCE_DIR="$HOME/.dotfiles/config"
DEST_DIR="$HOME/config"
# DEST_DIR="$HOME/.config"

# Create the destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

# Loop through each file in the source directory
for file in "$SOURCE_DIR"/*; do
  # Get the base filename
  filename=$(basename "$file")
  # Create a symlink in the destination directory
  ln -sfn "$file" "$DEST_DIR/$filename"
done

echo "Symlinks created in $DEST_DIR"
