#!/bin/sh
set -euo pipefail

cd ~/.system/nixos

if [ "${1-}" = "push" ]; then
    cd ..
    git add .
    git commit -m "Manual update on $(hostname)"
    git push
    cd nixos
else
    git pull
    nix flake update
    git add flake.lock
    git commit -m "$(hostname) system update"
    git push
fi
